### ISSUE TITLE
Slice method not required

### ISSUE THREAD

**Issue by tenasatupitsyn** [meggatrony/yuki#7]
Slice is not necessary in this part
https://github.com/meggatrony/yuki/blob/1c242ee13049215a325477467a647cd6330a5c74/core/commands/utility/hastebin.js#L16

Arguments are already handled here for from the first entry after the command
https://github.com/meggatrony/yuki/blob/1c242ee13049215a325477467a647cd6330a5c74/core/events/message.js#L3-L4

 **Tip**: check if there is any argument to continue publishing

**Comment by meggatrony** [comment]
Could you contact me?

**Comment by tenasatupitsyn** [comment]
Fix it and look for me, I'll answer you.

**Comment by meggatrony** [comment]
Ready!
